### ISSUE TITLE
"move" command into RouterOS via api

### ISSUE THREAD

**Issue by izzzhoga** [ansible-collections/community.routeros#145]
Hi everyone,

I can't figure out how to implement the following command using Community.Routeros (it's important to use the api instead of ssh):
/radius move [/radius find address={{RADIUS_SERVER}}] destination=0
I know how to do add, remove, update, query via API, but I don't know how to do move.
Help please

Hope this is enough info.

Regards
Ilya

**Comment by felixfontein** [comment]
You should be able to do this using the `cmd` option of community.routeros.api (https://ansible-collections.github.io/community.routeros/branch/main/api_module.html#parameter-cmd). Maybe something like this:
```yaml
- community.routeros.api:
    path: radius
    cmd: find address={{ RADIUS_SERVER }}
  register: result
- community.routeros.api:
    path: radius
    cmd: move {{ result.message[0][".id"] }} 0
```
(totally untested...)
