### ISSUE TITLE
api_modify: Some routes shows "changed" when they shouldn't

### ISSUE THREAD

**Issue by Igorgro** [ansible-collections/community.routeros#148]
##### SUMMARY

Some routes (I currently experiencing this only in `ip dhcp-client`, but there can be more) show `changed`, when there actually no changes. For example when I executing the following task muliple times:
```yaml
- name: Set DHCP client
  community.routeros.api_modify:
    path: ip dhcp-client
    data:
      - interface: ether1
        add-default-route: True
        default-route-distance: 1
        disabled: false
        use-peer-dns: True
        use-peer-ntp: True
        dhcp-options: ""
```
it always shows `changed` status, when no actually changes are performed (it is visible when enabling verbose output and comparing old_data and new_data)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`community.routeros.api_modify`

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection         Version
------------------ -------
community.routeros 2.5.0  
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
- Control host:
   -  OS: Arch Linux
    - Python version: 3.10.9
- Mikrotik RouterOS 7.7

##### STEPS TO REPRODUCE

Run a playbook with the task that modifies `ip dhcp-client` path of Mikrotik router

```yaml 
- name: Set DHCP client
  community.routeros.api_modify:
    path: ip dhcp-client
    data:
      - interface: ether1
        add-default-route: True
        default-route-distance: 1
        disabled: false
        use-peer-dns: True
        use-peer-ntp: True
        dhcp-options: ""
```

##### EXPECTED RESULTS
The status of task should be `ok`, not `changed` when applying the same configuration

##### ACTUAL RESULTS

```paste below
PLAY RECAP *************
localhost                  : ok=0    changed=1
```
