### ISSUE TITLE
Different manage RouterOS v6 and v7 via API

### ISSUE THREAD

**Issue by izzzhoga** [ansible-collections/community.routeros#155]
##### SUMMARY
Hello!
For a long time we have been developing roles and playbooks for RouterOS v6, both for ssh and for the api.

Now we have to support devices with RouterOS v7. Unfortunately, the code we have already written does not work with this version of RouterOS, although it would be logical that device management via the api should not change from version to version.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible-collections/community.routeros.api_modify

##### ANSIBLE VERSION
```
ansible [core 2.13.6]
  config file = /home/user/mkt/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
Collection         Version
------------------ -------
community.routeros 2.4.0
```

##### STEPS TO REPRODUCE
For RouterOS 6.49.7, this role works correctly, but for RouterOS 7.6 it ends with an error. It is logical to assume that the interaction with the device via the api should not change from version to version.

```
- name: For set module_defaults
  block:


    - name: Configure ntp
      community.routeros.api_modify:
        path: system ntp client
        data:
          - enabled: yes
            server-dns-names: time.google.com,0.pool.ntp.org,1.pool.ntp.org,2.pool.ntp.org,3.pool.ntp.org
            primary-ntp: "{{ ntp_server_list[0] }}"
            secondary-ntp: "{{ ntp_server_list[1] }}"

    - name: Configure timezone
      community.routeros.api_modify:
        path: system clock
        data:
          - time-zone-autodetect: no
            time-zone-name: manual

    - name: Configure timezone manual
      community.routeros.api_modify:
        path: system clock manual
        data:
          - time-zone: +0{{ timezone_shift }}:00

  
  module_defaults:
    group/community.routeros.api:
      hostname: '{{ inventory_hostname }}'
      password: '{{ service_user_ans_pass }}'
      username: '{{ service_user_ans_login }}'
      tls: true
      force_no_cert: false
      validate_certs: false
      validate_cert_hostname: false
```

##### ACTUAL RESULTS
```
TASK [MKT/mkt-config-ntp : Configure ntp] ***********************************************************************************************************
fatal: [mikrotik1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ca_path": null,
            "data": [
                {
                    "enabled": true,
                    "primary-ntp": "0.0.0.0",
                    "secondary-ntp": "1.1.1.1",
                    "server-dns-names": "time.google.com,0.pool.ntp.org,1.pool.ntp.org,2.pool.ntp.org,3.pool.ntp.org"
                }
            ],
            "encoding": "ASCII",
            "ensure_order": false,
            "force_no_cert": false,
            "handle_absent_entries": "ignore",
            "handle_entries_content": "ignore",
            "hostname": "mikrotik1",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "path": "system ntp client",
            "port": null,
            "timeout": 10,
            "tls": true,
            "username": "user",
            "validate_cert_hostname": false,
            "validate_certs": false
        }
    },
    "msg": "Error while modifying: unknown parameter server-dns-names"
}
```
