### ISSUE TITLE
Support for routing table?

### ISSUE THREAD

**Issue by itrack** [ansible-collections/community.routeros#162]
##### SUMMARY
The "routing table" is not supported by api_modify

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
routing table

##### ADDITIONAL INFORMATION
[https://help.mikrotik.com/docs/display/ROS/Policy+Routing](https://help.mikrotik.com/docs/display/ROS/Policy+Routing)

```yaml
    - name: Add routing tables
      community.routeros.api_modify:
        path: routing table
        data: 
          - "name='to_wan}' fib=''"
```
