### ISSUE TITLE
file set command issue (asks for '=')

### ISSUE THREAD

**Issue by gray380** [ansible-collections/community.routeros#164]
##### SUMMARY

Hello!

I try upload ssh public key to the mikrotik (RouterOS v7.6 stable) in the following way:
```yml
    - name: Generate empty ssh pub key
      community.routeros.api:
        path: "file"
        cmd: "print file=id_rsa.pub"

    - name: Put content to the ssh pub key
      community.routeros.api:
        path: "file"
        cmd: 'set id_rsa.pub.txt contents="{{ ssh_pub_key }}"'
```
The following error has appeared:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible_collections.community.routeros.plugins.module_utils.quoting.ParseError: missing '=' after 'id_rsa.pub.txt'
```
Under routeros cli comannds:
```
/file print file=id_rsa.pub
/file set id_rsa.pub contents="test"
```

work as expected.

Any help will be appreciated.

regards
Serhiy.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.routeros.api

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.4]
  config file = /Users/gray/projects/ansible/routers/ansible.cfg
  configured module search path = ['/Users/gray/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/gray/projects/ansible/venv/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/gray/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/gray/projects/ansible/venv/bin/ansible
  python version = 3.9.6 (default, Mar 10 2023, 20:16:38) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/Users/gray/projects/ansible/venv/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
ansible-galaxy collection list community.routeros

# ~/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
community.routeros 2.8.0

# ~/projects/ansible/venv/lib/python3.9/site-packages/ansible_collections
Collection         Version
------------------ -------
community.routeros 2.8.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = ~/projects/ansible/routers/ansible.cfg
DEFAULT_HOST_LIST(~/projects/ansible/routers/ansible.cfg) = ['/Users/gray/projects/ansible/routers/hosts.yml']
```

##### OS / ENVIRONMENT

ProductName:		macOS
ProductVersion:		13.3.1
BuildVersion:		22E261

##### STEPS TO REPRODUCE

```yaml
    - name: Generate empty ssh pub key
      community.routeros.api:
        path: "file"
        cmd: "print file=id_rsa.pub"
    - name: Put content to the ssh pub key
      community.routeros.api:
        path: "file"
        cmd: 'set id_rsa.pub.txt contents="{{ ssh_pub_key }}"'
```

##### EXPECTED RESULTS

Contents from variable should be placed into the file.

##### ACTUAL RESULTS

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible_collections.community.routeros.plugins.module_utils.quoting.ParseError: missing '=' after 'id_rsa.pub.txt'

```paste below
TASK [Put content to the ssh pub key] *************************************************************************************************************
fatal: [mikrotik]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"~//.ansible/tmp/ansible-local-22960vt0f6yot/ansible-tmp-1681564975.694714-23025-254122928642250/AnsiballZ_api.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"~//.ansible/tmp/ansible-local-22960vt0f6yot/ansible-tmp-1681564975.694714-23025-254122928642250/AnsiballZ_api.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"~//.ansible/tmp/ansible-local-22960vt0f6yot/ansible-tmp-1681564975.694714-23025-254122928642250/AnsiballZ_api.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.routeros.plugins.modules.api', init_globals=dict(_module_fqn='ansible_collections.community.routeros.plugins.modules.api', _modlib_path=modlib_path),\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/p2/xtr9ql715bd78nvs0v71x25m0000gn/T/ansible_community.routeros.api_payload_n8r02h0l/ansible_community.routeros.api_payload.zip/ansible_collections/community/routeros/plugins/modules/api.py\", line 577, in <module>\n  File \"/var/folders/p2/xtr9ql715bd78nvs0v71x25m0000gn/T/ansible_community.routeros.api_payload_n8r02h0l/ansible_community.routeros.api_payload.zip/ansible_collections/community/routeros/plugins/modules/api.py\", line 573, in main\n  File \"/var/folders/p2/xtr9ql715bd78nvs0v71x25m0000gn/T/ansible_community.routeros.api_payload_n8r02h0l/ansible_community.routeros.api_payload.zip/ansible_collections/community/routeros/plugins/modules/api.py\", line 365, in __init__\n  File \"/var/folders/p2/xtr9ql715bd78nvs0v71x25m0000gn/T/ansible_community.routeros.api_payload_n8r02h0l/ansible_community.routeros.api_payload.zip/ansible_collections/community/routeros/plugins/modules/api.py\", line 547, in api_arbitrary\n  File \"/var/folders/p2/xtr9ql715bd78nvs0v71x25m0000gn/T/ansible_community.routeros.api_payload_n8r02h0l/ansible_community.routeros.api_payload.zip/ansible_collections/community/routeros/plugins/modules/api.py\", line 414, in list_to_dic\n  File \"/var/folders/p2/xtr9ql715bd78nvs0v71x25m0000gn/T/ansible_community.routeros.api_payload_n8r02h0l/ansible_community.routeros.api_payload.zip/ansible_collections/community/routeros/plugins/module_utils/quoting.py\", line 201, in convert_list_to_dictionary\nansible_collections.community.routeros.plugins.module_utils.quoting.ParseError: missing '=' after 'id_rsa.pub.txt'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

**Comment by NikolayDachev** [comment]
I think this is a bug .. If I not mistake there is a check for .id and the code  mistake it with **id**_rsa.pub.txt
Will double check and will try to fix it

**Comment by NikolayDachev** [comment]
> I think this is a bug .. If I not mistake there is a check for .id and the code mistake it with **id**_rsa.pub.txt Will double check and will try to fix it

Ou sorry my mistake, actually this is related to something else .. not a code issue .. 
after cmd 1st arg .. for any  other  '=' is mandatory ..related to to ros API it self .. will check for solution how this can be structure properly 

```
cmd: 'set id_rsa.pub.txt contents="{{ ssh_pub_key }}"'
```

**Comment by NikolayDachev** [comment]
Hi, 

Using 'numbers=' can solve your problem .. as general almost everything in ROS is key=value pair 

@gray380 please test it in this way 

```
/file set  numbers=id_rsa.pub.txt contents="test"
```

```
 - name: Put content to the ssh pub key
      community.routeros.api:
        path: "file"
        cmd: 'set numbers=id_rsa.pub.txt contents="{{ ssh_pub_key }}"'
```

Let me know if this work for you
Regards

**Comment by ivoruetsche** [comment]
Hi

I have more or less the same problem. I just want to create a directory if it doesn't exists.

First I tried to do it on a simple way:
```
- name: Check and create if not exists
  community.routeros.api:
    path: file
    cmd: ":if ([ print count-only where {{ item }} ] = 0) do={ add {{ item }} }"
  loop:
    - type=directory name=firmware
    - type=directory name=backup
    - type=directory name=config
```
but this ends with `FAILED! => {"changed": false, "msg": "Found unexpected \"(\""}`
I didn't found any way to solve it, so I try it with two steps, first get the count and if it's 0, create it:
```
- name: Resolve the count of existing directory
  community.routeros.api:
    path: file
    cmd: print count-only where {{ item }}
  loop:
    - type=directory name=firmware
    - type=directory name=backup
    - type=directory name=config
```
But these ends with:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible_collections.community.routeros.plugins.module_utils.quoting.ParseError: missing '=' after 'count-only'
fatal: [192.168.2.124 -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):
  File "/home/x/.ansible/tmp/ansible-tmp-1734625493.5576978-2415551-174512743205787/AnsiballZ_api.py", line 107, in <module>
    _ansiballz_main()
  File "/home/x/.ansible/tmp/ansible-tmp-1734625493.5576978-2415551-174512743205787/AnsiballZ_api.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/x/.ansible/tmp/ansible-tmp-1734625493.5576978-2415551-174512743205787/AnsiballZ_api.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.routeros.plugins.modules.api', init_globals=dict(_module_fqn='ansible_collections.community.routeros.plugins.modules.api', _modlib_path=modlib_path),
  File "/usr/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.routeros.api_payload_l5483pan/ansible_community.routeros.api_payload.zip/ansible_collections/community/routeros/plugins/modules/api.py", line 581, in <module>
  File "/tmp/ansible_community.routeros.api_payload_l5483pan/ansible_community.routeros.api_payload.zip/ansible_collections/community/routeros/plugins/modules/api.py", line 577, in main
  File "/tmp/ansible_community.routeros.api_payload_l5483pan/ansible_community.routeros.api_payload.zip/ansible_collections/community/routeros/plugins/modules/api.py", line 369, in __init__
  File "/tmp/ansible_community.routeros.api_payload_l5483pan/ansible_community.routeros.api_payload.zip/ansible_collections/community/routeros/plugins/modules/api.py", line 551, in api_arbitrary
  File "/tmp/ansible_community.routeros.api_payload_l5483pan/ansible_community.routeros.api_payload.zip/ansible_collections/community/routeros/plugins/modules/api.py", line 418, in list_to_dic
  File "/tmp/ansible_community.routeros.api_payload_l5483pan/ansible_community.routeros.api_payload.zip/ansible_collections/community/routeros/plugins/module_utils/quoting.py", line 201, in convert_list_to_dictionary
ansible_collections.community.routeros.plugins.module_utils.quoting.ParseError: missing '=' after 'count-only'
", "module_stdout": "", "msg": "MODULE FAILURE
See stdout/stderr for the exact error", "rc": 1}
```

Nice would be to have the "file" path in the community.routeros.api_modify module. Or what is the best way to just create a directory?

Thanks a lot
Ivo
