### ISSUE TITLE
Support new paths for RouterOS 6.x.x

### ISSUE THREAD

**Issue by izzzhoga** [ansible-collections/community.routeros#182]
##### SUMMARY
Hello! When using RouterOS 6.x.x, I used paths to configure my Mikrotik (/routing ospf network), but with the advent of my Mikrotik with RouterOS 7.x.x, I have to "split" the code, since a different path to similar settings is used.

Are there plans to support old paths (for RouterOS 6.x.x) in modules such as community.routeros.api_modify?

Now for RouterOS 6.x.x I use the community.routeros.command module, and for RouterOS 7.x.x I use the community.routeros.api_modify module, which is very inconvenient for me.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`community.routeros.api_modify`

##### ADDITIONAL INFORMATION
For example:
```
- name: Configure ospf network for RouterOS 6.x.x
  community.routeros.api_modify:
    path: routing ospf network
    data:
      - some_data: "{{ some_variable }}"
```
