### ISSUE TITLE
Cannot add new entry to this path: user group

### ISSUE THREAD

**Issue by radokristof** [ansible-collections/community.routeros#256]
I cannot add user groups with the 'user group' API path:
```
FAILED! => {"changed": false, "msg": "Cannot add new entry name=\"admin\" to this path"}
```

Corresponding task:
```
- name: Configure User groups
  community.routeros.api_modify:
    path: user group
    handle_absent_entries: ignore
    handle_entries_content: remove_as_much_as_possible
    data:
      - name: admin 
        policy: local,telnet,ssh,ftp,reboot,read,write,policy,test,winbox,password,web,sniff,sensitive,api,romon,rest-api
      - name: operator
        policy: local,ssh,ftp,reboot,read,write,test,winbox,web,sniff,romon,!telnet,!policy,!password,!sensitive,!api,!rest-api
```
