### ISSUE TITLE
Routeros tasks switch to paramiko transport ignoring any settings

### ISSUE THREAD

**Issue by gitatr** [ansible-collections/community.routeros#27]
##### SUMMARY
It is pretty unclear to me, why paramiko is even used here, so I file this as a bug report. Ansible uses normal ssh binary, except when I try to run routeros tasks. Then it requires the  paramiko lib for some reason, which does not use my `~/.ssh/config` and has all kinds of its own issues. I grepped through this repo if paramiko appears anywhere but cannot find it.
I am now thoroughly puzzled. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible-playbook, community.routeros.command

##### ANSIBLE VERSION
```
ansible --version
ansible 2.10.8
  config file = None
  configured module search path = ['/home/at/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = <....> venv/lib/python3.8/site-packages/ansible
  executable location = <...> venv/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
<empt>
```

##### OS / ENVIRONMENT
Linux XXXX 5.4.0-66-lowlatency #74-Ubuntu SMP PREEMPT Wed Jan 27 23:41:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE
* in fresh python venv:
* pip install ansible
* create minimal example inventory with one router and one "normal" linux host
```
[routers]
router ansible_host=192.168.88.1

[routers:vars]
ansible_connection=ansible.netcommon.network_cli
connection=network_cli
ansible_network_os=community.routeros.routeros
ansible_user=admin
gather_facts=no
ansible_gather_facts=no
ansible_python_interpreter=auto_silent

[servers]
someserver    ansible_host=someserver
```

playbook:

```yaml
---
- name: RouterOS test with network_cli connection
  hosts: routers
  gather_facts: false
  tasks:

  # Run a command and print its output
  - community.routeros.command:
      commands:
        - /system resource print
    register: system_resource_print
  - debug:
      var: system_resource_print.stdout_lines

  # Retrieve facts
  - community.routeros.facts:
  - debug:
      msg: "First IP address: {{ ansible_net_all_ipv4_addresses }}"
      
- name: TestSomethingElse
  hosts: servers
  tasks:
    - shell: uptime
      register: some_output
    - debug: var=some_output.stdout_lines
```

##### EXPECTED RESULTS
Run without errors

##### ACTUAL RESULTS
* the routeros task:
```
<snip>
 ___________________________________
< TASK [community.routeros.command] >
 -----------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [router]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python2.7"}, "changed": false, "msg": "paramiko is not installed: No module named 'paramiko'"}
```
* the "normal" linux host task runs without issues

After `pip install paramiko`

* runs without issues

After `pip uninstall paramiko`
* error reappears

After trying running ansible-playbook with forced `ssh` transport e.g. :  `ANSIBLE_TRANSPORT=ssh ansible-playbook -i hosts simplexample.yml`
* error still there
