### ISSUE TITLE
Modify address lists without affecting others

### ISSUE THREAD

**Issue by ewysong** [ansible-collections/community.routeros#283]
##### SUMMARY
Ability to modify address-lists without affecting others. I'm sure this would apply to other areas as well, such as /ip/address if an interface has more than one address.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
I've tried both community.routeros.api_modify and community.routeros.api_find_and_modify to try and make this work, but I've not found a way to modify an address list from /ip/firewall/address-list to include only the addresses listed in the playbook and to not remove any other address lists in the configuration.

##### ADDITIONAL INFORMATION

``` 
- name: Firewall list
  delegate_to: localhost
  community.routeros.api_modify:
    path: ip firewall address-list
    data:
      - list: example_list
        address: 192.168.1.0/24
      - list: example_list
        address: 192.168.2.0/24
```

If I add ```handle_absent_entries: remove```, then it removes any other address lists in the configuration but not listed in the playbook. I'd like to just remove any addresses in the address list itself that are not in the configuration.
