### ISSUE TITLE
Add support for `interface ethernet switch rule` to `api_modify` module

### ISSUE THREAD

**Issue by dmaes** [ansible-collections/community.routeros#319]
##### SUMMARY

Would love to see support for the `interface ethernet switch rule` path in `api_modify`module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

api_modify

##### ADDITIONAL INFORMATION

Personal use-case: VLAN assignments based on MAC address

```yaml
- name: Configure ethernet switch rules
  community.routeros.api_modify:
    hostname: "{{ routeros_hostname }}"
    username: "{{ routeros_username }}"
    password: "{{ routeros_password }}"
    handle_absent_entries: remove
    handle_entries_content: remove_as_much_as_possible
    path: interface ethernet switch rule
    data:
      - switch: switch1
        ports: ether7
        src-mac-address: A4:12:6D:77:94:43/FF:FF:FF:FF:FF:FF
        new-vlan-id: 200
```
