### ISSUE TITLE
New task module for configuring

### ISSUE THREAD

**Issue by jplitza** [ansible-collections/community.routeros#33]
##### SUMMARY

Add a new task module that makes it easier to idempotently modify RouterOS config.

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

Currently, it's a huge PITA to idemtpotently modify RouterOS config. My roles have RouterOS script snippets like this all over the place, to be executed via CLI:
```
:if ([/ip firewall filter find chain=forward action=fasttrack-connection] = "") do={/ip firewall filter add chain=forward action=fasttrack-connection connection-state=established,related ipsec-policy=out,none} else={/ip firewall filter set [find chain=forward action=fasttrack-connection] ipsec-policy=out,none}
```
This looks for a firewall rule in the forward chain with action "fasttrack-connection". If it finds such a rule, it sets "ipsec-policy=out,none" on it. If it doesn't find such a rule, it adds one.

Obviously it's quite impossible to catch all edge cases (especially ordering etc.), because RouterOS config is damn complex. But I'd imagine something like this:

```yaml
- community.routeros.config:
    path: /ip firewall filter
    attributes:
      chain: forward
      action: fasttrack-connection
      connection-state: established,related
      ipsec-policy: out,none
    match:
      - chain
      - action
```
One could also think about adding more parameters, like "place-before" (ideally accepting something like `[find ...]`), which would obviously only be used for adding, not for updating.

Or is there a more elegant way to do this?
