### ISSUE TITLE
[Question] How to make DNS entry as static

### ISSUE THREAD

**Issue by Nerus87** [ansible-collections/community.routeros#336]
As in the thread, how make an entry as static DNS by using API calls from Anisble?

Path: /ip/dhcp-server/lease

Example SSH command:
```- name: Get {{ container_name }} mac-address
  community.network.routeros_command:
   commands: :put [/ip/dhcp-server/lease/ get ([find where host-name={{ container_name }}]) mac-address]
  register: mac```

**Comment by felixfontein** [comment]
You should be able to use the api_info module (https://docs.ansible.com/ansible/devel/collections/community/routeros/api_info_module.html with `include_dynamic=true`) and some Jinja to find the `id` of the entry you want to convert, and then use the api module (https://docs.ansible.com/ansible/devel/collections/community/routeros/api_module.html) to call `make-static` for that entry.

**Comment by Nerus87** [comment]
I was able to find entry by the host-name, but in current API I will not be able to find host-name (not existing)

`#- name: Get {{ container_name }} mac-address
#  community.network.routeros_command:
#    commands: :put [/ip/dhcp-server/lease/ get ([find where host-name=srv-sourcebans-test]) mac-address]
#    register: mac_address
#  when: ansible_network_os == 'community.network.routeros'`

**Comment by felixfontein** [comment]
Have you tried the `unfiltered` option of community.routeros.api_info?

**Comment by Nerus87** [comment]
> Have you tried the `unfiltered` option of community.routeros.api_info?

Yeah, this was a reason, sorry for not responding asap but still fighting with scripting.
I was able to find it based on host-name (it was a mess and I spent the whole day to find the reason).
So if you even have a problem with dashes in names use this site to check your query and save my time: https://mixedanalytics.com/tools/jmespath-expression-tester/

```
- name: Get DHCP lease list
  community.routeros.api_info:
    hostname: "{{ hostname }}"
    password: "{{ password }}"
    username: "{{ username }}"
    path: ip dhcp-server lease
    include_dynamic: true
    unfiltered: true
    hide_defaults: false
  register: leases

- name: Filter leases list and set lease id
  set_fact:
    lease_id: "{{ leases.result | json_query(query) }}"
  vars:
    query: "[?\"host-name\"== '{{ container_name }}'].\".id\""
```
