### ISSUE TITLE
"interface wifi provisioning" with multiple entries

### ISSUE THREAD

**Issue by ivoruetsche** [ansible-collections/community.routeros#344]
##### SUMMARY
We try to define with `community.routeros.api_modify` three CAPsMAN provisioning entries, but only one is accepted, because the attribute `action` didn't accept `create-dynamic-enabled` multiple time in the data part of the yaml.

Coresponding RouterOS configuration:
```
/interface wifi provisioning add action=create-dynamic-enabled comment=prov_yyy-zz-aaa01_min disabled=no identity-regexp="^test-zz-nnn01-ap[0-9][0-9]_l" master-configuration=cfg_yyy-lan_min slave-configurations=cfg_yyy-guest_min,cfg_yyy-test_min
/interface wifi provisioning add action=create-dynamic-enabled comment=prov_yyy-zz-aaa01_mid disabled=no identity-regexp="^test-zz-nnn01-ap[0-9][0-9]_m" master-configuration=cfg_yyy-lan_mid slave-configurations=cfg_yyy-guest_mid,cfg_yyy-test_mid
/interface wifi provisioning add action=create-dynamic-enabled comment=prov_yyy-zz-aaa01_max disabled=no identity-regexp="^test-zz-nnn01-ap[0-9][0-9]_h" master-configuration=cfg_yyy-lan_max slave-configurations=cfg_yyy-guest_max,cfg_yyy-test_max
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`community.routeros.api_modify`

##### ANSIBLE VERSION

```paste below
ansible [core 2.17.8]
```

##### COLLECTION VERSION

```paste below
# /usr/lib/python3/dist-packages/ansible_collections
Collection         Version                          
------------------ -------                          
community.routeros 2.20.0                           
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

`Router OS 7.17.2`

##### STEPS TO REPRODUCE

```yaml
- name: mik_switch | mik_switch_capsman.yaml | interface wifi provisioning
  community.routeros.api_modify:
    hostname: "192.168.0.124"
    password: "x"
    username: "admin"
    path: interface wifi provisioning
    handle_absent_entries: remove
    handle_entries_content: remove_as_much_as_possible
    data:
      - identity-regexp: ^test-zz-nnn01-ap[0-9][0-9]_l
        action: create-dynamic-enabled
        comment: prov_yyy-zz-aaa01_min
        disabled: False
        master-configuration: cfg_yyy-lan_min
        slave-configurations: cfg_yyy-guest_min,cfg_yyy-test_min
      - identity-regexp: ^test-zz-nnn01-ap[0-9][0-9]_m
        action: create-dynamic-enabled
        comment: prov_yyy-zz-aaa01_mid
        disabled: False
        master-configuration: cfg_yyy-lan_mid
        slave-configurations: cfg_yyy-guest_mid,cfg_yyy-test_mid
      - identity-regexp: ^test-zz-nnn01-ap[0-9][0-9]_h
        action: create-dynamic-enabled
        comment: prov_yyy-zz-aaa01_max
        disabled: False
        master-configuration: cfg_yyy-lan_max
        slave-configurations: cfg_yyy-guest_max,cfg_yyy-test_max
  register: res
  delegate_to: localhost
```

##### EXPECTED RESULTS

Creating three new provisioning entries:
- prov_yyy-zz-aaa01_min
- prov_yyy-zz-aaa01_mid
- prov_yyy-zz-aaa01_max

##### ACTUAL RESULTS

```paste below
fatal: [192.168.0.124 -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ca_path": null,
            "data": [
                {
                    "action": "create-dynamic-enabled",
                    "comment": "prov_yyy-zz-aaa01_min",
                    "disabled": false,
                    "identity-regexp": "^test-zz-nnn01-ap[0-9][0-9]_l",
                    "master-configuration": "cfg_yyy-lan_min",
                    "slave-configurations": "cfg_yyy-guest_min,cfg_yyy-test_min"
                },
                {
                    "action": "create-dynamic-enabled",
                    "comment": "prov_yyy-zz-aaa01_mid",
                    "disabled": false,
                    "identity-regexp": "^test-zz-nnn01-ap[0-9][0-9]_m",
                    "master-configuration": "cfg_yyy-lan_mid",
                    "slave-configurations": "cfg_yyy-guest_mid,cfg_yyy-test_mid"
                },
                {
                    "action": "create-dynamic-enabled",
                    "comment": "prov_yyy-zz-aaa01_max",
                    "disabled": false,
                    "identity-regexp": "^test-zz-nnn01-ap[0-9][0-9]_h",
                    "master-configuration": "cfg_yyy-lan_max",
                    "slave-configurations": "cfg_yyy-guest_max,cfg_yyy-test_max"
                }
            ],
            "encoding": "ASCII",
            "ensure_order": false,
            "force_no_cert": false,
            "handle_absent_entries": "remove",
            "handle_entries_content": "remove_as_much_as_possible",
            "handle_read_only": "error",
            "handle_write_only": "create_only",
            "hostname": "192.168.0.124",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "path": "interface wifi provisioning",
            "port": null,
            "restrict": null,
            "timeout": 10,
            "tls": false,
            "username": "admin",
            "validate_cert_hostname": false,
            "validate_certs": true
        }
    },
    "msg": "Every element in data must contain a unique value for action. The value \"create-dynamic-enabled\" appears at least twice."
}
```
