### ISSUE TITLE
`api_modify` with non-unique `name`-fields in `routing bgp connection`

### ISSUE THREAD

**Issue by tim427** [ansible-collections/community.routeros#359]
##### SUMMARY

With `routing filter rule` you could add multiple entries with the same `chain`-field, but this doesn't work for `routing bgp connection` with the same `name`-field.
This actually works with WinBox, WebGUI and CLI, but via `community.routeros` each entry will be overwritten with each entry.

I'm not 100% sure if this behaviour is caused by the API implementation of RouterOS itself, of the `community.routeros` collection.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`community.routeros`

##### ANSIBLE VERSION

```paste below
ansible [core 2.17.10]
  config file = /home/tim/ansible/ansible.cfg
  configured module search path = ['/home/tim/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/tim/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Nov 30 2024, 21:22:50) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
$ ansible-galaxy collection list community.routeros

# /home/tim/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
community.routeros 3.5.0

# /usr/lib/python3/dist-packages/ansible_collections
Collection         Version
------------------ -------
community.routeros 2.20.0
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
---
- name: '(routeros) Add BGP connection'
  community.routeros.api_modify:
    path: 'routing bgp connection'
    ensure_order: false
    restrict:
      - field: 'name'
        regex: "{{ ix.name }}-as{{ peer.asn }}"
    data: "{{ lookup('template', 'bgp_connection.j2') | from_yaml }}"
...
```
output of rendered 'bgp_connection.j2':
```yaml
---
- name: "TESTIX-as123456"
  disabled: false
  as: 654321
  local.address: "192.0.2.123"
  local.role: 'ebgp-peer'
  input.limit-process-routes-ipv4: 250000
  remote.as: 123456
  remote.address: "192.0.2.253"
  router-id: "192.0.2.123"
  input.filter: "TESTIX-as123456-ipv4"
  output.filter-chain: "TESTIX-export"
  output.network: "TESTIX-output"
  routing-table: "ROUTINGTABLE"
  address-families: 'ip'
- name: "TESTIX-as123456"
  disabled: false
  as: 654321
  local.address: "192.0.2.123"
  local.role: 'ebgp-peer'
  input.limit-process-routes-ipv4: 250000
  remote.as: 123456
  remote.address: "192.0.2.254"
  router-id: "192.0.2.123"
  input.filter: "TESTIX-as123456-ipv4"
  output.filter-chain: "TESTIX-export"
  output.network: "TESTIX-output"
  routing-table: "ROUTINGTABLE"
  address-families: 'ip'
- name: "TESTIX-as123456"
  disabled: false
  as: 654321
  local.address: "2001:db8::123"
  local.role: 'ebgp-peer'
  input.limit-process-routes-ipv6: 250000
  remote.as: 123456
  remote.address: "2001:db8::253"
  router-id: "192.0.2.123"
  input.filter: "TESTIX-as123456-ipv6"
  output.filter-chain: "TESTIX-export"
  output.network: "TESTIX-output"
  routing-table: "ROUTINGTABLE"
  address-families: 'ipv6'
- name: "TESTIX-as123456"
  disabled: false
  as: 654321
  local.address: "2001:db8::123"
  local.role: 'ebgp-peer'
  input.limit-process-routes-ipv6: 250000
  remote.as: 123456
  remote.address: "2001:db8::254"
  router-id: "192.0.2.123"
  input.filter: "TESTIX-as123456-ipv6"
  output.filter-chain: "TESTIX-export"
  output.network: "TESTIX-output"
  routing-table: "ROUTINGTABLE"
  address-families: 'ipv6'
...
```

##### EXPECTED RESULTS

Four times a BGP connection with name `TESTIX-as123456`

##### ACTUAL RESULTS

Two times a BGP connection with name `TESTIX-as123456`; the last IPv4 and last IPv6 entry.

```paste below

```
