### ISSUE TITLE
Interface IPIP support

### ISSUE THREAD

**Issue by rondex** [ansible-collections/community.routeros#365]
##### SUMMARY

Add support to interface ipip to modules community.routeros.api_info and community.routeros.api_modify.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

community.routeros.api_info and community.routeros.api_modify

##### ADDITIONAL INFORMATION

Should make use of module by the "ansible way", meaning no need to deep knowledge of RouterOS specific commands.

```yaml

- name: Add interfaces
  hosts: all
  gather_facts: false
  module_defaults:
    group/community.routeros.api:
      hostname: "{{ api_hostname }}"
      username: "{{ api_username }}"
      password: "{{ api_password }}"
      # The following options configure TLS/SSL.
      # Depending on your setup, these options need different values:
      tls: true
      validate_certs: false
      validate_cert_hostname: true
      # If you are using your own PKI, specify the path to your CA certificate here:
      # ca_path: /path/to/ca-certificate.pem

  tasks:

    - name: IPIP intefaces
      community.routeros.api_modify:
        path: interface ipip # <--- Not supported yet
        handle_absent_entries: remove
        handle_entries_content: remove_as_much_as_possible
        # ensure_order: true
        data: "{{ interfaces.ipip }}"
      delegate_to: localhost

---
all:
  vars:
    interfaces:

     #...

      ipip:
        - name: ipip-1
          allow-fast-path: false
          clamp-tcp-mss: "yes"
          comment: "ipip-1"
          disabled: false
          dont-fragment: false
          ipsec-secret: "xxxx"
          keepalive: false
          local-address: "192.168.1.1"
          mtu: 1430
          remote-address: "10.10.10.10"
          # Other parameters...
```
