### ISSUE TITLE
Parameter not evaluated at community.routeros.api_modify

### ISSUE THREAD

**Issue by rondex** [ansible-collections/community.routeros#368]
##### SUMMARY

Bool parameter "fib" not evaluated. No matter which value set, it will always add a new routing table.

When using community.routeros.api_info, it returns an empty string when it's set to "yes" in router config, and "null" when "false"
```
ok: [rtr_temp -> localhost] => {
    "msg": {
        "changed": false,
        "failed": false,
        "result": [
            {
                "!comment": null,
                ".id": "*414",
                "fib": "",
                "name": "routing-table-a"
            },
            {
                "!comment": null,
                "!fib": null,
                ".id": "*415",
                "name": "routing-table-b"
            }
        ]
    }
}
```
When using "handle_absent_entries: remove", it removes all routing tables, and then add it all again, due to difference between  "fib": "" and  "fib": true.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.13]
  config file = /home/adminqwe/ansible/ansible-routeros-api/ansible.cfg
  configured module search path = ['/home/adminqwe/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/adminqwe/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/adminqwe/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/adminqwe/.local/bin/ansible
  python version = 3.9.21 (main, Dec  5 2024, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-2.0.1)] (/usr/bin/python3)
  jinja version = 3.1.6
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection         Version
------------------ -------
community.routeros 3.6.0  
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /home/user/ansible/ansible-routeros-api/ansible.cfg
DEFAULT_HOST_LIST(/home/user/ansible/ansible-routeros-api/ansible.cfg) = ['/home/user/ansible/ansible-routeros-api/inventory']
```

##### OS / ENVIRONMENT

```
cat /etc/redhat-release 
Red Hat Enterprise Linux release 9.5 (Plow)
```

##### STEPS TO REPRODUCE

```yaml
    - name: Routing tables
      community.routeros.api_modify:
        path: routing table
        handle_absent_entries: remove
        handle_entries_content: remove_as_much_as_possible
        # ensure_order: true
        data:
         - name: routing-table-a
           fib: true  #<--- HERE
           disabled: false
         - name: routing-table-b
           fib: false  #<--- HERE
           disabled: false
      delegate_to: localhost
```

##### EXPECTED RESULTS

It's expected to module "community.routeros.api_info" return for key "fib", value true if configured as yes, and false or null or !fib, otherwise.

Also, module "community.routeros.api_modify", should evaluate and set accordingly fib parameter.

##### ACTUAL RESULTS

```paste below

```
