### ISSUE TITLE
/interface/ethernet/power-cycle-ping-enabled: yes/true no/false missmatch

### ISSUE THREAD

**Issue by ivoruetsche** [ansible-collections/community.routeros#370]
Hi

Thanks a lot for the collection and your effort.

Ivo

##### SUMMARY

If we set /interface/ethernet/power-cycle-ping-enabled to "yes", Ansible always generate a change or if we set true, we get an error.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.18.5]
```

##### COLLECTION VERSION

```
Collection         Version
------------------ -------
community.routeros 3.6.0  
```

##### OS / ENVIRONMENT

PRETTY_NAME="Ubuntu 24.04.2 LTS"
RouterOS: 7.18.2

##### STEPS TO REPRODUCE

```
  - hostname: "192.168.1.2"
    password: "xxxxx"
    username: "admin"
    path: interface ethernet
    find:
      default-name: ether10
    values:
      power-cycle-ping-enabled: "yes"  # or "true"
```

##### EXPECTED RESULTS

If I set power-cycle-ping-enabled to yes (or true), there should be no change or error.

##### ACTUAL RESULTS

```
--- before
+++ after
-            "power-cycle-ping-enabled": true,
+            "power-cycle-ping-enabled": "yes",
changed: ....

```
If we set "true", we get an error:
`"Error while modifying for .id=*17: invalid value of power-cycle-ping-enabled, must be either yes or no"`
```
