### ISSUE TITLE
ip service changed in 7.19

### ISSUE THREAD

**Issue by ivoruetsche** [ansible-collections/community.routeros#372]
Hi

As the [release notes of 7.19](https://forum.mikrotik.com/viewtopic.php?t=216983) mention: "ip-service - show all TCP/UDP connections on the system;", something has changed and it has an impact of my ansible script.

On 7.18.2 the ip services looks like these:
```
[admin@sw01] > /ip/service/print 
Flags: X - DISABLED, I - INVALID
Columns: NAME, PORT, ADDRESS, CERTIFICATE, VRF, MAX-SESSIONS
#   NAME     PORT  ADDRESS         CERTIFICATE  VRF   MAX-SESSIONS
0 X telnet     23                               main            20
1   ftp        21                               main            20
2   www        80  192.168.2.0/24               main            20
                   10.1.0.0/16                                  
                   192.168.0.0/29                                 
3   ssh        22  192.168.2.0/24               main            20
                   10.1.0.0/16                                  
                   192.168.0.0/29                                 
4   www-ssl   443  192.168.2.0/24  none         main            20
                   10.1.0.0/16                                  
5   api      8728  192.168.2.0/24               main            20
6 X winbox   8291                               main            20
7   api-ssl  8729  192.168.2.0/24  none         main            20
[admin@sw01] >
``` 
On 7.19.1:
```
[admin@sw15] > /ip/service/print 
Flags: D - DYNAMIC; X - DISABLED, I - INVALID; c - CONNECTION
Columns: NAME, PORT, PROTO, ADDRESS, CERTIFICATE, VRF, MAX-SESSIONS, LOCAL, REMOTE
 #     NAME        PORT  PROTO  ADDRESS          CERTIFICATE  VRF   MAX-SESSIONS  LOCAL          REMOTE             
 0     ftp           21  tcp                                  main            20                                    
 1     ssh           22  tcp    192.168.2.0/24                main            20                                    
                                10.1.0.0/16                                                                       
                                192.168.52.0/26                                                                     
 2 D c ssh           22  tcp                                                      192.168.52.24  192.168.99.15:43438
 3  X  telnet        23  tcp                                  main            20                                    
 4 D   dhcp          67  udp                                                                                        
 5 D   dhcpclient    68  udp                                                                                        
 6     www           80  tcp    192.168.2.0/24                main            20                                    
                                10.1.0.0/16                                                                       
                                192.168.52.0/26                                                                     
 7 D   ntp          123  udp                                                                                        
 8     www-ssl      443  tcp    192.168.2.0/24   none         main            20                                    
                                10.1.0.0/16                                                                       
                                192.168.52.0/26                                                                     
 9 D   route_BFD   3784  udp                                                                                        
10 D   route_BFD   4784  udp                                                                                        
11  X  winbox      8291  tcp                                  main            20                                    
12     api         8728  tcp    192.168.2.0/24                main            20                                    
13     api-ssl     8729  tcp    192.168.2.0/24   none         main            20                                    
[admin@sw15] > 
```

We set the IP's etc. like this on ROS <7.19:
```
  - hostname: "192.168.52.24"
    password: "xxxxx"
    username: "admin"
    path: ip service
    find:
      name: api
    values:
      address: 192.168.2.0/24
```

This works on 7.19 only, if no connection on the specific service is active. If we have only 7.19 or never device, this could be done with an additional find argument `dynamic: no` - but, for the next 6 month or more, we have mixed versions. We can check the ROS version, but I decide to use a field where is available on both OS releases, like `max-sessions` or `vrf` and I tried to find the the entry with an "if vrf is not empty" or "if max-sessions > 0", but I haven't found how I have to implement it.
Some examples where I tried out:
```
    find:
      max-sessions: >0
      max-sessions: ">0"
      max-sessions: '>0"
      max-sessions: '\>0"
      vrf: !
      vrf: \!
      vrf: !=''
      vrf: !=""
      vrf: "!"
      vrf: "\!"
      vrf: "!=''"
      vrf: '!=""''
```
How do I have to implement it?

As a work around, we use "vrf: main", this is working for both versions (< = > 7.19), but very unnice.
```
  - hostname: "192.168.52.24"
    password: "xxxxx"
    username: "admin"
    path: ip service
    find:
      name: api
      vrf: main
    values:
      address: 192.168.2.0/24
```

Thanks for any hints

Ivo
