### ISSUE TITLE
[API] The comment breaks the work of the module

### ISSUE THREAD

**Issue by akimrx** [ansible-collections/community.routeros#44]
Of course, it was very funny to look for the cause of the error for so much time, but after looking at the source code, everything became clear.

Guys, we need to correct the division of the string into parameters, because the comment does not always consist of one word.

[The function that returns the error](https://github.com/ansible-collections/community.routeros/blob/a88f4c804b147136f9164e571408e90a649532e1/plugins/modules/api.py#L356)

[A function that incorrectly separates arguments](https://github.com/ansible-collections/community.routeros/blob/a88f4c804b147136f9164e571408e90a649532e1/plugins/modules/api.py#L380) and breaks down into `comment="some multiple string"`

**How to reproduce it?**  
Try to add a simple rule of the form:
```yaml
  community.routeros.api:
    hostname: "{{ mikrotik_host }}"
    username: "{{ mikrotik_user }}"
    password: "{{ mikrotik_password }}"
    path: ip firewall filter
    add: action=accept chain=forward comment='accept in ipsec policy' ipsec-policy=in,ipsec
```

The actual result will be an error when adding the rule, but by the way, this module does not understand its own errors at all and always returns OK, which is also funny and requires correction.

With the debug, I was able to see the true result of the execution and the essence of the "error":
```
    "msg": [
        "missing '=' after 'in'"
```

A few details:
```
ok: [localhost] => (item={'comment': 'accept in ipsec policy', 'id': 6, 'action': 'accept', 'chain': 'forward', 'options': 'ipsec-policy=in,ipsec'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "add": "action=accept chain=forward comment='accept in ipsec policy' ipsec-policy=in,ipsec",  <<< here
            "cmd": null,
            "hostname": "10.0.0.1",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "path": "ip firewall filter",
            "port": null,
            "query": null,
            "remove": null,
            "ssl": false,
            "update": null,
            "username": "ansible"
        }
    },
    "item": {
        "action": "accept",
        "chain": "forward",
        "comment": "accept in ipsec policy",
        "ipsec-policy: "in,ipsec"
    },
    "msg": [
        "missing '=' after 'in'"  <<< here
```
