### ISSUE TITLE
Extra lines in stdout

### ISSUE THREAD

**Issue by 1rV1N-git** [ansible-collections/community.routeros#62]
##### SUMMARY
When I send a command to the router I get a response from the router with extra lines. 
![image](https://user-images.githubusercontent.com/34376228/146521286-fac11c9e-886a-46ad-88f8-9f32dd431435.png)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
routeros

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/wsl/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below
[defaults]
stdout_callback = yaml
host_key_checking = False
retry_files_enabled = False
inventory = hosts.yaml
[persistent_connection]
connect_timeout = 30
command_timeout = 30
```

##### STEPS TO REPRODUCE

```yaml
- name: check user is exist
  hosts: mikrotik
  gather_facts: false
  tasks:
    - name: check user is exist
      community.routeros.command:
        commands: 
          - if ([/user find name=admin] !="") do={:put "exist"}
      register: exist

    - debug:
        var: exist
```

##### EXPECTED RESULTS
I want to get only output from line 3

##### ACTUAL RESULTS
I got 3 lines. First-line eq first letter of command, middle-lines = empty line(empty lines can be more than one), last line eq correct output.  

```paste below

```
