### ISSUE TITLE
Error 'identity' must be '.id' module community.routeros.api

### ISSUE THREAD

**Issue by registr76** [ansible-collections/community.routeros#67]
##### SUMMARY

Hello.

I am trying to get neighbor data through community.routeros.api.
When I add the "identity" field to the list, I get an error "'identity' must be '.id'". Is it supposed to be like this or is it a bug?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.routeros.api

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.7 (default, Nov 24 2021, 21:15:59) [GCC 10.3.1 20211027]
  jinja version = 3.0.3
  libyaml = False
```

##### COLLECTION VERSION

```paste below
# /usr/lib/python3.9/site-packages/ansible_collections
Collection         Version
------------------ -------
community.routeros 2.0.0 
```

##### CONFIGURATION

```paste below
DEFAULT_ASK_PASS(/etc/ansible/ansible.cfg) = False
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/root/ansible/hosts.yaml']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

```
routerboard: yes
board-name: SXT 2
model: RBSXTG-2HnD
revision: r3
serial-number: E2230F5EDF77
firmware-type: ar9344L
factory-firmware: 6.47.10
current-firmware: 6.47.10
upgrade-firmware: 6.46.
```

##### STEPS TO REPRODUCE

```yaml
    - name: Get "ip neighbor query" {{ inventory_hostname }}
      community.routeros.api:
        hostname: "{{ ansible_host }}"
        port: "{{ api_port }}"
        password: "{{ ansible_password }}"
        username: "{{ ansible_user }}"
        path: "ip neighbor"
        query: ".id address mac-address identity"
      register: neighbor_list
```

##### EXPECTED RESULTS

I need to get the IP addresses and names of devices connected to the AP via WDS. To do this, I request data from the list of /ip neighbors: ip address, mac-address, record .id and identity. Further I process by mac-address.

##### ACTUAL RESULTS

As a result I get an error.

```paste below
fatal: [tmp5-1]: FAILED! => {"changed": false, "msg": ["'identity' must be '.id'"]}
```
