### ISSUE TITLE
RouterOS - issue with routeros_facts when interface has a space in name

### ISSUE THREAD

**Issue by danpospisil** [ansible-collections/community.routeros#8]
##### SUMMARY

When an interface has a space in its name, the routeros_facts module will fail. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

routeros

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = None
  configured module search path = ['/home/daniel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]
```

##### CONFIGURATION

```paste below
no changes
```

##### OS / ENVIRONMENT

Windows 10, Ubuntu WSL 1

##### STEPS TO REPRODUCE

1) change an interface name to: "spaces in name"
2) run the example playbook

```yaml
- name: Mikrotik Playbook
  hosts: all
  gather_facts: no
  tasks:
  - name: Get Facts
    routeros_facts:
      gather_subset: all
```

##### EXPECTED RESULTS

No crash should occur

##### ACTUAL RESULTS

Ansible will crash - it extracts not the whole name when spaces are present in it

```paste below
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: u'spaces'
```
To fix this I have changed the extraction regexp in routeros_facts.py file:
function parse_name:
`match = re.search(r'name=\"([\w\d\-\s]+)\"', data, re.M)`
function parse_interface:
`match = re.search(r'\sinterface=([\w\d\-\s]+[\w\d\-])\s', data, re.M)`

**Comment by zagi-tng** [comment]
Similar happens when using routeros_command and there is a interface list delimited with comma

for example:

community.network.routeros_command:
    commands: /interface wireless cap set caps-man-names=WIFI_Manager1,WIFI_Manager2 discovery-interfaces=ether1 interfaces=wlan1,wlan2 enabled=yes

..

          "<_02 discovery-interfaces=ether1 interfaces=wlan1",
                "<_02 discovery-interfaces=ether1 interfaces=wlan1",
                "",
                "expected command name (line 1 column 1)"
            ],
            [
                "bad command name wlan2 (line 1 column 1)"

**Comment by felixfontein** [comment]
@zagi-tng this could also be caused by line wrapping. You could try adding `+cet512w` to your RouterOS username (see 3. in https://docs.ansible.com/ansible/devel/collections/community/routeros/docsite/ssh-guide.html#important-notes).

**Comment by virtualguy** [comment]
I can reproduce the issue with commas too, looks like its splitting it into different commands on the comma. Fixed by wrapping the command in single quotes

**Comment by felixfontein** [comment]
BTW, this issue is about community.routeros.facts, not about community.routeros.command.

In any case, you seem to be supplying a string to the `commands` argument of community.routeros.command, which expects a **list** and not a string. Ansible helps you by splitting a string along comma into a list. If you don't want to do that, supply a **list** with one element instead:

```.yaml
- community.routeros.command:
    commands:
      - put command here
```

**Comment by zagi-tng** [comment]
> Fixed by wrapping the command in single quotes


yes. that works.
and i use 'username+cet1024w'

```
tasks:
    - name: executes bootstrap commands
      community.network.routeros_command:
        commands:
        - '/interface wireless cap set discovery-interfaces=ether1 enabled=yes caps-man-names=WIFI_Manager02,WIFI_Manager01 interfaces=wlan1,wlan2'
        - '/interface ethernet set [ find default-name=ether1 ] auto-negotiation=yes speed=1Gbps tx-flow-control=off rx-flow-control=off'
        - '/ip service set ftp disabled=yes'
....
```
